Unit test aziz
xpayeg/Android-kotlin-sdk pull request #17
Opened 2020-10-27 08:24 UTC by MahmoudAziz1996

2020-10-27 09:48 UTC, IRostom requested changes
i left 10 comments on the tests with problems, please make sure to check them all.

2020-10-27 09:48 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
> +    }
This assertion is not enough.
You need to assert that XpayUtils.activePaymentMethods is equal to MutableList<PaymentMethods> that contains payment methods based on  the response you enque. 

For example, if you enque a response that includes card, cash, and kiosk.
you need to assert that xpayutils,activePaymentMethods equal to a  MutableList<PaymentMethods> that contains card, cash , and kiosk.

2020-10-27 09:48 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
> +        val prepareAmountResponseBody = FileUtils.readTestResourceFile("PrepareAmountResponse.json")
remove this

2020-10-27 09:48 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
> +    }
lik ethe above test you need to assert that XpayUtils.PaymentOptionsTotalAmounts is equal to the expected object

2020-10-27 09:48 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
> +
this is not a test, either set it to expect a thrown error or assertion

2020-10-27 09:48 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
> +
btw this test is for server error not network error

2020-10-27 09:48 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
>      }
this test (pay returns an error when the payment method is not available in payment options)
how are you testing this if you are not setting the available payment options firs?

2020-10-27 09:48 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
you need to set available payment options otherwise it fails because it's empty not because the user information is missing

2020-10-27 09:48 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
> +    }
this is not a test, where is the assertion ?

2020-10-27 09:48 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
> +    }
again where is the test ?

2020-10-27 09:48 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
> +    }
where is the test brdo ?

2020-10-27 10:40 UTC, MahmoudAziz1996 commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
> +        val prepareAmountResponseBody = FileUtils.readTestResourceFile("PrepareAmountResponse.json")
this regards to what ? @IRostom

2020-10-27 10:42 UTC, IRostom commented on app/src/test/java/com/xpay/kotlinutils/XpayUtilsTest.kt
> +        val prepareAmountResponseBody = FileUtils.readTestResourceFile("PrepareAmountResponse.json")
line 84

2020-11-02 13:53 UTC, IRostom approved these changes
Great job ya man, I will do some changes and merge it into develop.

@MahmoudAziz1996

2020-11-03 12:28 UTC, merged